### ISSUE TITLE
Issue with a vital application question

### ISSUE THREAD

**Issue by SandKing1** [voidbydefault/EasyApplyBot#10]
Hi

For job such as this one https://www.linkedin.com/jobs/view/3664038172.

it will ask something like "are you legally authorised to work in XXXX" and present a drop box.

The bot will always select NO in the dropbox. This question comes up a lot. Any way to add functionality for question ?

**Comment by voidbydefault** [comment]
The functionality is already here. See line 118

```
# Are you legally authorized to work in COUNTRY? (yes/no checkbox)
legallyAuthorized: False
```

Please go through the `config.yaml` thoroughly, it has many options already. Closing this thread.
