### ISSUE TITLE
Premium user (reports already applied on all jobs) | Bot applies to first relevant job on page, then skips the rest of the page

### ISSUE THREAD

**Issue by ejlaw** [voidbydefault/EasyApplyBot#16]
Hello,

I am noticing that for every page, the bot applies to the first relevant job that it finds on the page and then pastes this:

```
Going to job page 0
Starting the application process for this page...
Applying to the job....
Failed to upload resume or cover letter!
Done applying to the job!
Already applied to the job!
Already applied to the job!
...
Already applied to the job!
Already applied to the job!
Applying to jobs on this page has been completed!
Sleeping for 626.6820077896118 seconds.

```
It then repeats this for every page after. I am not seeing any error messages at all. I have also confirmed that these are NEW jobs that are posted and I could not have possibly already applied to them. Could this be some of my settings that are causing this? Thank you!

**Comment by voidbydefault** [comment]
Hi,

> Already applied to the job!

Means job was applied. Not an issue. Share screenshots if you believe otherwise: 

![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/adfb28ed-c7ba-42b5-9d57-bc52ca1f8a26)

**Comment by ejlaw** [comment]
Well, it is an issue because I have not applied to any of these jobs before. I can pick an entirely new category for job search and it always just applies to the very first job on the list and then says 'already applied' to every other job below it and then it starts a new page. I just confirmed it by picking a new 'position' in the config, one that I have never done before, and it has the same issue.

![image](https://github.com/voidbydefault/EasyApplyBot/assets/142347274/3f85aae8-0809-47bb-8969-e224088acc3d)

**Comment by voidbydefault** [comment]
Are you on premium account?

**Comment by ejlaw** [comment]
Yes

**Comment by voidbydefault** [comment]
Ask someone to test using free account. Seems to be an isolated issue on premium users. Unfortunately, I don't have any means to test the code on premium accounts (a free user here) so might not be able to help.

**Comment by ejlaw** [comment]
Okay, I will see if I can find one, test it and give an update. Thanks!

**Comment by salomonj11** [comment]
It's not a premium user problem. I have encountered the same error. It's somehow related to the config remote under locations. If I use a city like 'Los angeles' instead of remote the problem does not happen. 

For some reason when it uses the remote location after a job it applied the bot is not able to click to the next item and starts saying that all the jobs left already have been applied for but it's not true.

**Comment by voidbydefault** [comment]
@salomonj11 

Set `remote: False` if you are on older code (newer one has it disabled) and searching **remote** in `Locations:` is also not an issue (see https://github.com/voidbydefault/EasyApplyBot/issues/13#issuecomment-1673999906 and https://github.com/voidbydefault/EasyApplyBot/issues/13#issuecomment-1674009592).

**Comment by ejlaw** [comment]
@voidbydefault I am still running into the problem with the above changes. It applies to one, then fails for the rest of the page. I will post my config file and a screenshot below:

[config.yaml.txt](https://github.com/voidbydefault/EasyApplyBot/files/12370449/config.yaml.txt)

![image](https://github.com/voidbydefault/EasyApplyBot/assets/142347274/82a9aab7-14d7-48b4-8ee7-0c10c7cc13a2)

**Comment by voidbydefault** [comment]
@ejlaw 
Don't put `remote` as first location. Add a country first then remote as a location. Try this and confirm.

**Comment by voidbydefault** [comment]
I am unable to produce this issue of "false applied". This is today's test run:

![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/98b49168-182c-4f52-ab9b-e66094e58033)

And this is since Feb-23:
![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/27c0ec31-27d5-41ba-b286-02b73468a81c)

**Comment by ejlaw** [comment]
@voidbydefault Does yours work using my config?

**Comment by voidbydefault** [comment]
Yes. It does. 

```
Starting the search for Legal Assistant in Canada.
Going to job page 0
Starting the application process for this page...
Applying to the job....
Done applying to the job!
Applying to the job....
```

![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/b7a4ff12-36c3-4e98-9d44-5e904d0431ab)

Just don't put `remote` as first location. I won't be responding on this thread, it's not an issue. I can't provide personal technical support. Don't mind. Closing.
