### ISSUE TITLE
Chrome driver version

### ISSUE THREAD

**Issue by naanrdk** [voidbydefault/EasyApplyBot#17]
Won't run with latest chrome browser

![image](https://github.com/voidbydefault/EasyApplyBot/assets/13908439/e8d152b0-f8ad-4a86-ac8f-0d3a30a257ac)

**Comment by naanrdk** [comment]
And with version 114.0.5735.90

![image](https://github.com/voidbydefault/EasyApplyBot/assets/13908439/0faad5c8-b745-4f40-84a2-95eb3ec2f8ce)

**Comment by voidbydefault** [comment]
Chromedriver used by bot is set to autodownload latest available version and if you get any error, it's upstream issue. Anyhow, below what i just ran to reproduce the problem. It's working fine for me.

* Ensure your Google Chrome browser is fully updated
* Mine is: Version 116.0.5845.97 (Official Build) (64-bit)

![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/dc9d6342-25a5-49e2-8f48-f79b5f35669d)

Issue is not related to bot. Closing.
