### ISSUE TITLE
Some fields are simply filled with zero or answer as no even after adding its answer in config file.

### ISSUE THREAD

**Issue by RajeshreeTMehta** [voidbydefault/EasyApplyBot#18]
I have added my experience in Project Management as 9 years and in others as required specifically. Also I have mentioned my notice period. However, it answers zero when asked in a question format on the website like "How many years of experience you have as a Project Manager?" or it can also be "Your total years of experience as Project Manager? " The bot simply answers it as zero. Also when any question is asked "Are you comfortable in working Japan timing?" My answer would be yes, but the bot simply selects "No" there. How can we be so specific on giving answers to the bot. It is possible that bot asks us for the input when it doesn't have answer to anything or it takes a pause for us to enter the information and then it takes it ahead. Later, it records all the questions and the answers in its own records and then it answers by itself next time such question occurs again. 

Please let me know how can we solve this?

**Comment by voidbydefault** [comment]
Depends how you updated your `experience:` in `config.yaml`. For example, for bot "Project Management" is NOT same as "Project Manager". Hence consider adding relevant permutations like suggested below and add something for `default` also so bot uses that value for everything else.

```
# ------------ Additional parameters: years of experience ---------------
# How many years of work experience do you have ...? (whole numbers only)
# You may add more skills depending on your industry or profession at the bottom.
experience:
 - Project Manager
 - Project Management
 - Managing Projects
 - ...
 - ...
 -  # default to put for any industry/skill that you did not list
 default: 20
```

For "work hours", set following to `True` so if bot detects `confortable` whether as experience or commute or job hours, it will answer yes.

```
 # Are you comfortable commuting to this job's location? (yes/no checkbox)
 commute: True
```

This is not an issue. Closing this thread.
