### ISSUE TITLE
Bot is getting stuck on math questions

### ISSUE THREAD

**Issue by megamango** [voidbydefault/EasyApplyBot#21]
I don't know if they are from the company or if LinkedIn is inserting them to prevent bots but it's working.  They are simple questions such as "To ensure you have read all of the screening questions, enter the result of 2+7 as the answer to this question." and the bot just gets stuck.  I understand it might be involved to recognise and solve these questions, but at least an exception handler would be appreciated so it doesn't get stuck.  Like, the bot has been on this application for 30 minutes; discard and move on.  

Related to this, when the bot gets stuck on a question, it fills the unprepared_questions.csv with copies until the bot is stopped.  I have 3000 copies of the question above from about 2 hours of stuck.

**Comment by voidbydefault** [comment]
> To ensure you have read all of the screening questions, enter the result of 2+7 as the answer to this question

This sounds more like an employer-specific question than a LinkedIn one. If you note bot being stuck on an application, either fill in that answer manually or close the application by clicking on [x] so bot may proceed to the next job.

**Comment by EasyApplyBotUser** [comment]
> > To ensure you have read all of the screening questions, enter the result of 2+7 as the answer to this question
> 
> This sounds more like an employer-specific question than a LinkedIn one. If you note bot being stuck on an application, either fill in that answer manually or close the application by clicking on [x] so bot may proceed to the next job.

Is there a way to make the bot automatically close the application when it gets stuck?

**Comment by voidbydefault** [comment]
> Is there a way to make the bot automatically close the application when it gets stuck?
Working on it. Can you share the error text you're getting? It should be something like `enter a valid (whatever)`.
