### ISSUE TITLE
csv output

### ISSUE THREAD

**Issue by Casplat** [voidbydefault/EasyApplyBot#22]
Hello, 

I've configured the bot and it does work however, the output csv file does not include the company name leaving the column blank. Also, is it possible to separate the date and time in to separate columns? 

This is how it looks like for example:
![image](https://github.com/voidbydefault/EasyApplyBot/assets/145500330/27440428-a091-427f-9f7a-5507344dd74b)

**Comment by voidbydefault** [comment]
Hi,

I also noted in some cases it doesn't capture the name but generally does. Please see the % where it failed to capture company name. For date and time, did you try [BI dashboard](https://github.com/voidbydefault/EasyApplyBot/tree/master/BI) available in this repository?

**Comment by voidbydefault** [comment]
I just double-checked. My instance of bot has applied to about ~24K jobs, with blank company names being ~7K (roughly 30%). I don't see it as a priority, so I won't be working on it. I can't say why it's failing to scrape names in some cases.

Below is a visual from the PowerBI dashboard, so you may see names captured. I would strongly advise you to deploy (all you need to do is change the path to your bot directly).

![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/e299291a-4278-41ee-9785-947a465bb64e)

**Comment by Casplat** [comment]
I was able to run the bot again and make the required updates to the BI file. Although the company name doesn't show in the csv, it does in the power bi file which is fine by me. I was worried that since it isn't showing in the csv that it wouldn't in BI for tracking purposes. It does (not sure how) so I think I'm good to go! Thanks Again for your time and work on this! You're helping many people!

**Comment by voidbydefault** [comment]
@Casplat Same issue is reported again, I am investigating, see #30

**Comment by Casplat** [comment]
Thank you for looking into this and making the necessary changes. I will be sure to update my files and re-run the bot.
