### ISSUE TITLE
The location I am searching always chooses somewhere random. 

### ISSUE THREAD

**Issue by DevJChen** [voidbydefault/EasyApplyBot#24]
For some reason when I run this code, it instantly sleeps and I get this Traceback when I am running the code. Why does this happen? Also everytime I check the browser, I see that the location that is being searched for jobs of this nature is places like Latin America, and APJ for example, but I never had those countries in the locations porton for the config.yaml. 

Sleeping for 894.12597823143 seconds.
Traceback (most recent call last):
  File "C:\Pycharm Projects\EasyApplyBot\linkedineasyapply.py", line 83, in start_applying
    self.apply_jobs(location)
  File "C:\Pycharm Projects\EasyApplyBot\linkedineasyapply.py", line 131, in apply_jobs
    raise Exception("Nothing to do here, moving forward...")
Exception: Nothing to do here, moving forward...

**Comment by voidbydefault** [comment]
> Random locations

Send me the snippet of your `locations:` from `config.yaml`. No one reported this behavior.

> Exception: Nothing to do here, moving forward...

This suggestions you are handling on a page with no jobs found hence "nothing to do here".
