### ISSUE TITLE
company field is empty output_*.csv

### ISSUE THREAD

**Issue by frankxxu** [voidbydefault/EasyApplyBot#30]
![image](https://github.com/voidbydefault/EasyApplyBot/assets/22988536/1b14f1b1-e777-4e2c-956d-899feb850531)

**Comment by voidbydefault** [comment]
Thanks for bringing this up. You're the second the person to report so it seems there is some change frorm LinkedIn. I will review and update asap.

**Comment by voidbydefault** [comment]
The issue is fixed, please redownload `linkedineasyapply.py`. Reason was a change at LinkedIn's job results page.
