### ISSUE TITLE
unable to run - can you please help

### ISSUE THREAD

**Issue by dalavinikhil** [voidbydefault/EasyApplyBot#33]
:\LinkedIn\EasyApplyBot\venv\Scripts\python.exe C:\LinkedIn\EasyApplyBot\main.py 
Traceback (most recent call last):
  File "C:\LinkedIn\EasyApplyBot\main.py", line 135, in <module>
    parameters = validate_yaml()
  File "C:\LinkedIn\EasyApplyBot\main.py", line 96, in validate_yaml
    assert len(parameters['positions']) > 0
TypeError: object of type 'NoneType' has no len()

Process finished with exit code 1

**Comment by boss00786** [comment]
yes facing same issue.

**Comment by voidbydefault** [comment]
Error is clear:
> assert len(parameters['positions']) > 0
> TypeError: object of type 'NoneType' has no len()

You need to define positions in `config.yaml`. Make sure you have configured your profile properly, bot won't do that for you. Watch this video: https://youtu.be/IXflenwJzhQ?si=V46i1_-2zQOxjjlw
