### ISSUE TITLE
Error while running the code. local interpreter is unable to use the same name for the folder belongs to Venv 

### ISSUE THREAD

**Issue by SALMANAHMEDHASHMI** [voidbydefault/EasyApplyBot#38]
![Untitled](https://github.com/voidbydefault/EasyApplyBot/assets/1109222/73ee9f71-6de1-4205-be4a-37e3b7922949)
Hi,

First i want to say the path for virtual interpreter is not showing me button OK until i will change the name of the "Venv" if i change the name of "Venv" to something else it work and after that i will receive the error on the code mentioned below:

 After running i am having this issue:
C:\Users\Salman\bot\EasyApplyBot\venvv\Scripts\python.exe C:\Users\Salman\bot\EasyApplyBot\main.py 
Traceback (most recent call last):
  File "C:\Users\Salman\bot\EasyApplyBot\main.py", line 5, in <module>
    from validate_email import validate_email
ModuleNotFoundError: No module named 'validate_email'

Process finished with exit code 1

So i think my problem lies first with the interpreter, guide me how to solve it.

**Comment by voidbydefault** [comment]
This is not an issue. Delete current `vent` folder and set your own interpreter (see my video from ReadMe) and install requirements to get going.  Closing.
