### ISSUE TITLE
Getting Good amount of issues

### ISSUE THREAD

**Issue by HunterCustom** [voidbydefault/EasyApplyBot#39]
Just installed and followed the video guide. I failed my first time around due to not entering positions or locations. update that and now getting these errors. 

In terms of Lines 43 and 44 Colum 1, This is how I have entered it.
![image_2023-11-26_142601432](https://github.com/voidbydefault/EasyApplyBot/assets/26927519/2b86b9d1-80ff-4cf8-90ef-7ff8962e6cf9)

`Traceback (most recent call last):
  File "C:\Users\hunte\EasyApplyBot\main.py", line 136, in <module>
    parameters = validate_yaml()
                 ^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\main.py", line 36, in validate_yaml
    raise exc
  File "C:\Users\hunte\EasyApplyBot\main.py", line 34, in validate_yaml
    parameters = yaml.safe_load(stream)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config.yaml", line 43, column 1
could not find expected ':'
  in "config.yaml", line 44, column 1
`

**Comment by dmike23** [comment]
> Just installed and followed the video guide. I failed my first time around due to not entering positions or locations. update that and now getting these errors.
> 
> In terms of Lines 43 and 44 Colum 1, This is how I have entered it. ![image_2023-11-26_142601432](https://private-user-images.githubusercontent.com/26927519/285676586-2b86b9d1-80ff-4cf8-90ef-7ff8962e6cf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMjgzMjQsIm5iZiI6MTcwMTAyODAyNCwicGF0aCI6Ii8yNjkyNzUxOS8yODU2NzY1ODYtMmI4NmI5ZDEtODBmZi00Y2Y4LTkwZWYtN2ZmODk2MmU2Y2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDE5NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMjU1ZWU3N2FmMjgxMWIyYTJiODVkMDRkMjU0ZjUyMGQ5MjNjOGZiZjZhYjdjZGNkZDRjNmMxYzgxZmQ0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yrxeyTbIqdtJJeS46cXOeeXzgjGylFDrpSfnqFWRFzs)
> 
> `Traceback (most recent call last): File "C:\Users\hunte\EasyApplyBot\main.py", line 136, in <module> parameters = validate_yaml() ^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\main.py", line 36, in validate_yaml raise exc File "C:\Users\hunte\EasyApplyBot\main.py", line 34, in validate_yaml parameters = yaml.safe_load(stream) ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\__init__.py", line 125, in safe_load return load(stream, SafeLoader) ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\__init__.py", line 81, in load return loader.get_single_data() ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data node = self.get_single_node() ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node document = self.compose_document() ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document node = self.compose_node(None, None) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node node = self.compose_mapping_node(anchor) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node item_value = self.compose_node(node, item_key) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\composer.py", line 64, in compose_node if self.check_event(AliasEvent): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event self.current_event = self.state() ^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value if not self.check_token(KeyToken, ValueToken, BlockEndToken): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\scanner.py", line 115, in check_token while self.need_more_tokens(): ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens self.stale_possible_simple_keys() File "C:\Users\hunte\EasyApplyBot\venv\Lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys raise ScannerError("while scanning a simple key", key.mark, yaml.scanner.ScannerError: while scanning a simple key in "config.yaml", line 43, column 1 could not find expected ':' in "config.yaml", line 44, column 1 `

Try adding commas to your positions... does it fix it?

**Comment by voidbydefault** [comment]
Correctly pointed out by @dmike23, I emphasized in the video not changing format or adding or deleting spaces. Redo your `config.yaml` and only change the parameters without adding or deleting `-` signs or `spaces`.

Not an issue. Closing.
