### ISSUE TITLE
Drop down list commute question and Adding company employee number filter

### ISSUE THREAD

**Issue by hazemimo** [voidbydefault/EasyApplyBot#4]
Hi Taimur,

Thank you again for your effort!

For the example I mentioned, the job link is https://www.linkedin.com/jobs/view/3649282950/

As I mentioned, I'm trying to add a filter to filter out the employee population to filter out 11-50 employees, as most of them are scam companies. I have traced the class for the population number on the page, but I don't know how to add the function in the code. The class is: 

<li class="jobs-unified-top-card__job-insight">
                  <div class="flex-shrink-zero mr2 t-black--light">
                    
    <div class="ivm-image-view-model   ">
        
    <div class="ivm-view-attr__img-wrapper ivm-view-attr__img-wrapper--use-img-tag display-flex
        
        ">
        <li-icon aria-hidden="true" type="company" class=" " size="large"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" data-supported-dps="24x24" fill="currentColor" class="mercado-match" width="24" height="24" focusable="false">
  <path d="M4 2v20h16V2zm14 18h-4v-2h-4v2H6V4h12zm-7-8H8v-2h3zm0 4H8v-2h3zm5-4h-3v-2h3zm-5-4H8V6h3zm5 0h-3V6h3zm0 8h-3v-2h3z"></path>
</svg></li-icon>
    </div>
  
          </div>
  
                  </div>
                  <span>
                    ### 11-50 employees · Marketing Services
                  </span>
                </li>

Could you please add a function to let the bot filter the population?

Thank you!

**Comment by voidbydefault** [comment]
Thanks for the submission, @hazemimo. This is not an issue; probably using the "Discussion" section would have been a better place. However, regarding your query filters offered by LinkedIn, they are:

- Date posted
- Experience level
- Company
- Job type
- On-site/remote
- Easy Apply
- Location
- Industry
- Job function
- Title
- Under-10 applicants
- In your network
- Commitments

Filtering by company size without it being a `filter` (as a field) would require a bot to scrape the webpage, which makes it a bit complicated. In case you think a company is scammy, you may use the `*.csv` logs generated by the bot to shortlist such companies and add them to the `blacklist` section of `config.yaml`. It's not a proactive solution, but it serves its purpose in the long run. Similarly, you can add `job poster` to `blacklist` so the bot would ignore jobs posted by blacklisted people.

**Comment by hazemimo** [comment]
I was trying to make it happen in the same way as how the blacklist work. By scraping the size of the company. I have reached that the Xpath of the size is /html/body/div[4]/div[3]/div[4]/div/div/main/div/div[2]/div/div[2]/div[1]/div/div[1]/div/div[1]/div[1]/div[3]/ul/li[2]/span/text()

It would be very helpful if you'd like to work on this together to add a function to filter the size. As it is a function that LinkedIn never provides. Let me know if you'd like to arrange a zoom call or something, I think I'm very close to the solution!

**Comment by voidbydefault** [comment]
Hi @hazemimo ,

Apologies for the delay in responding; I've been quite busy.

Finding the web element is one part of it; how do you intend to implement a filter that users can change according to their preferences when the default or valid values acceptable to the website aren't known?

I suggest that you fork my repo, and once you are able to progress on this idea, send a pull request for merging. Also, I am working on a few other improvements to the bot's functionality whenever I get the time. Due to my full-time job and other commitments, it's difficult to schedule a call. 

Your interest in improving the bot is much appreciated. Stay in touch. Thanks.
