### ISSUE TITLE
No module named 'yaml'

### ISSUE THREAD

**Issue by Tibzyyy** [voidbydefault/EasyApplyBot#44]
I have issues with first code lines, It won't load the pluggins. I tried on two different computers using your step by step process.

Here is the error:

Traceback (most recent call last):
  File "D:\Téléchargements\EasyApplyBot-master\EasyApplyBot-master\source\app\main.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

Also, when I open requirements.txt for the first time, each tim it is already in Orange as if I already installed the pluggins (using the run command neither works).

![Capture d'écran 2023-12-06 175900](https://github.com/voidbydefault/EasyApplyBot/assets/153544313/152e62a1-400c-4e14-8ab5-6760f519e849)

**Comment by voidbydefault** [comment]
Refer `ReadMe` -- it is there for a reason. If you want a simplier solution, try using Windows executable version of bot. You will only need to configure `config.yaml`.

Not an issue. Closing.
