### ISSUE TITLE
After updating to latest code I faced errors.

### ISSUE THREAD

**Issue by Hunt3r5** [voidbydefault/EasyApplyBot#46]
C:\Users\Demigod\bot\EasyApplyBot\venv\Scripts\python.exe C:\Users\Demigod\bot\EasyApplyBot\source\app\main.py 
Traceback (most recent call last):
  File "C:\Users\Demigod\bot\EasyApplyBot\source\app\main.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

Process finished with exit code 1

**Comment by Hunt3r5** [comment]
This is after installing manually all requirements.

C:\Users\Demigod\bot\EasyApplyBot\venv\Scripts\python.exe C:\Users\Demigod\bot\EasyApplyBot\source\app\main.py 
Traceback (most recent call last):
  File "C:\Users\Demigod\bot\EasyApplyBot\source\app\main.py", line 137, in <module>
    parameters = validate_yaml()
  File "C:\Users\Demigod\bot\EasyApplyBot\source\app\main.py", line 97, in validate_yaml
    assert len(parameters['positions']) > 0
TypeError: object of type 'NoneType' has no len()

Process finished with exit code 1

**Comment by voidbydefault** [comment]
> File "C:\Users\Demigod\bot\EasyApplyBot\source\app\main.py", line 97, in validate_yaml
assert len(parameters['positions']) > 0

You have problems in `config.yaml`, did you define any positions?

This is not an update issue. Closing.

**Comment by Elefantex** [comment]
> > File "C:\Users\Demigod\bot\EasyApplyBot\source\app\main.py", line 97, in validate_yaml
> > assert len(parameters['positions']) > 0
> 
> You have problems in `config.yaml`, did you define any positions?
> 
> This is not an update issue. Closing.

I have not any problem with config.yaml, it is done properly, its something that happens, Ive tried with different laptops and always happens
