### ISSUE TITLE
Issue after search screen

### ISSUE THREAD

**Issue by Elefantex** [voidbydefault/EasyApplyBot#47]
So I have this issue where the bot after going to the Search jobs screen, opens the Windows menu, and then closes it.
So it doesn't apply to any job, the console doesn't show any error.

**Comment by Hunt3r5** [comment]
Same here for me i got error in main.py 

Traceback (most recent call last):
  File "main.py", line 137, in <module>
  File "main.py", line 97, in validate_yaml
TypeError: object of type 'NoneType' has no len()
[11296] Failed to execute script 'main' due to unhandled exception!

**Comment by voidbydefault** [comment]
Fix:
Setup your `config.yaml` properly, bot has no issues. 

**Test:**
I just did a test run, and here is a screenshot at 8:57 PM, 29-Dec (my local time).

![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/a27d3d1b-4fb3-49db-9c03-2d07bfc2d2c0)

**To see errors in console, run the bot in console/terminal. Do this:**

Step 1:
![Screenshot 2023-12-29 205506](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/7c4af5b2-670c-4517-bcad-50b665d622a0)

Step 2:
![Screenshot 2023-12-29 205519](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/3ba92af8-f9c9-4a85-9392-19274132c32b)

By the time, I am done writing this reponse; this is the performance of bot. 
![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/db5e6e10-4aef-47c9-9671-f807bb6056e0)

Hence confirming:
1. Not a bot issue. 
2. Fix your `config.yaml`. 
3. Please don't treat `issues` page as personal tech support. 

Closing.

**Comment by Elefantex** [comment]
![image](https://github.com/voidbydefault/EasyApplyBot/assets/46497564/56cf38b6-05e4-4079-adfc-c483f61de21a)
This is the console after I press ctrl + C after a while because it is not applying.
this the config, I have changed to config.txt because .yaml is not allowed and Ive replaced the personal info
[configTXT.txt](https://github.com/voidbydefault/EasyApplyBot/files/13796306/configTXT.txt)

**Comment by voidbydefault** [comment]
Your `config.yaml` is fine and bot is working, here is the evidence. 

![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/c0f33818-1817-4476-ac02-2db0101ee399)

If you read the text thrown by bot specially lines like "no more jobs to apply" and "sleeping for [xxx] seconds" means bot can't do anyything. Refine your search criteria. Remove `remote`, etc. Try and fail, and try again. You're a web dev/programmer.

I won't be responding to this thread anymore.
