### ISSUE TITLE
I'm running into these issues 

### ISSUE THREAD

**Issue by anewcoderhasarrived** [voidbydefault/EasyApplyBot#5]
When running the bot I got these issues, what should I change these to?

line 119, in <module>
    parameters = validate_yaml()

line 76, in validate_yaml
    assert len(parameters['positions']) > 0
TypeError: object of type 'NoneType' has no len()

**Comment by voidbydefault** [comment]
You're failing `config.yaml` validation checks relating to `positions`.  You should be adding at least one position without the hash # sign. For example:

```
positions:
 - sales man
 - sales representative
#- ...

```
If you wish to add more, use next line, ad a space then hyphen sign then space and add a position. 

The bot is not an issue relating to bot hence closing it.

**Comment by SandKing1** [comment]
hello , I am running into the same issues.

My Config file is setup on position correctly as per below.

ositions:
 - Data Analyst
locations:
 - Australia
 #- A second location
 #- A third location
 #- ...
 - Remote
distance: 25

Please help

**Comment by SandKing1** [comment]
Hi,

Please dis-regard the above issue.

I solved it. Just had to re-save the config file.
