### ISSUE TITLE
When Internship option on "experienceLevel" set to True, Internship Option on "jobTypes" is automatically set to True even if it is False.

### ISSUE THREAD

**Issue by walid-physics** [voidbydefault/EasyApplyBot#51]
Hi, 

The issue is when Internship option on "experienceLevel" set to True, Internship Option on "jobTypes" is automatically set to True even if it is False.

Thanks,

**Comment by voidbydefault** [comment]
Hi, is it same as #49?

**Comment by walid-physics** [comment]
I guess they might be related.
