### ISSUE TITLE
error/problem with EasyApplyBot.exe

### ISSUE THREAD

**Issue by komangulo** [voidbydefault/EasyApplyBot#52]
When I run the EasyApplyBot.exe program I get the following error and the application does not work.
What is the solution or what should I do?

![Capasdawdwdtura](https://github.com/voidbydefault/EasyApplyBot/assets/43007108/2b3098a3-7a30-4e13-9808-518fa635563b)

**Comment by voidbydefault** [comment]
Have you populated your `config.yaml` correctly?

**Comment by TATUMTOT** [comment]
I'm having the same issues Also having an issue running it from source.

**Comment by voidbydefault** [comment]
@TATUMTOT if you are having an issue while running frfom source besides the *.exe then it's definitely something wrong with your `config.yaml`. Source as well as the executable, both are tested extensively.

Not an issue. Closing.
