### ISSUE TITLE
Dropdown unprepared questions?

### ISSUE THREAD

**Issue by jalalshabo** [voidbydefault/EasyApplyBot#53]
Sometimes unprepared questions require a dropdown, but the experience section where I leave the correct answers for unprepared questions requires numbers. How do I set the correct answer for these dropdown questions in the config file?

**Comment by voidbydefault** [comment]
Bot converts the defined paramters in `config.yaml` to float and integers for use during the application process. It has a low chance of failure but if it does, bot moves onto next job in line. Possible for you to share screenshot of the portion where it's showing error?

Note: Remember to hide personal info (if any).

**Comment by jalalshabo** [comment]
I don't think you understood my issue. Everything works great but sometimes there are questions requiring clicking a dropdown box and the config file accepts only numbers for question-answer inputs. Is there a way to correctly click on the needed dropdown answer, or does it just not have this functionality?

**Comment by voidbydefault** [comment]
Bot scans for the keywords and answers dropdowns. If there is any `unprepared question` and its a very frequent one, I can consider adding it. BUT which question is it and how many times bot failed on it? It's a featuree request, not an issue. Closing.
