### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by arabinowe** [voidbydefault/EasyApplyBot#54]
https://www.linkedin.com/jobs/view/3749264738/
 
 Looks like it gets stuck on answering today's date.

**Comment by voidbydefault** [comment]
Not a bug, it's just bot cannot answer all questions and is designed to terminate the stuck applications. In the above job has "today's date" as an optional filed, not sure where it would stuck. If possible share screenshot with personal info hidden.

**Comment by voidbydefault** [comment]
No response. Not a bug anyways. 

Closing.
