### ISSUE TITLE
Where is the job_title in yml file

### ISSUE THREAD

**Issue by mistertest** [voidbydefault/EasyApplyBot#56]
Hello thank you for your fork of this python Apply bot. 

I hope that I will can particapting, if I understand the code and concept more better.
I don't hnow whare the "job_title "  word is placed in yaml , I see only the black list title.

So how the input about the job title in form search  in linkedin will be fill  ? 

I just want indicate my Job title like " Developer Full Stack" 
in the input concerned in linkedin and be focus only about jobas with this title.

Normaly Job title is about this line in  linkedinapply.py , that's it ? 

```
for job_tile in job_list:
            job_title, company, poster, job_location, apply_method, link = "", "", "", "", "", ""
```

Tnank you for your answer.

**Comment by MrJamieMcC** [comment]
You place your job titles in the positions section. The YAML file explains everything in good detail

```
# Remove hash sign to add positions. You can add as many as you need, but preserve formatting
positions:
 #- First position
 #- A second position
 #- A third position
 #- ...
```
