### ISSUE TITLE
How can I use the script  with a  TEST MODE

### ISSUE THREAD

**Issue by mistertest** [voidbydefault/EasyApplyBot#57]
Hello, thank you a lot for your work. 

My second question is about the idea to having a special test Mode.: 
How can I test the script just for one apply , and target just one job with a specific link  ? 

I don't want to apply massive jobs, just for testing ans see how the script is working, so there is a solution for that ?

Thx

**Comment by voidbydefault** [comment]
Hi @mistertest ,

Thanks. You will have to tinker with the link path in `linkedinapply.py`. You will have to form a link so the bot only opens it, ignoring everything else (it won't be straight-forward and will require some Python knowledge).

Not an issue. Closing.
