### ISSUE TITLE
Pulling latest updates, now it won't find my config.yaml file...?

### ISSUE THREAD

**Issue by dmike23** [voidbydefault/EasyApplyBot#61]
I pulled the latest updates, updated the config file, saved and now when i run main.py its not finding/validating the config file...? Any ideas what could cause this?

**Comment by dmike23** [comment]
![image](https://github.com/voidbydefault/EasyApplyBot/assets/17505146/288bf749-615d-4f0b-8e2f-89f99f9d2907)

**Comment by voidbydefault** [comment]
You will need to handle the `config.yaml` path, `main.py` is unable to find it as mentioned in the error:

![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/29269f63-4f5a-41c7-9f4a-ff2f2cd3682b)
