### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by syosry** [voidbydefault/EasyApplyBot#62]
![Screen Shot 2024-07-08 at 11 06 29 PM](https://github.com/voidbydefault/EasyApplyBot/assets/175078880/72321983-c975-4ab4-880a-8083d2c9f004)

**Comment by voidbydefault** [comment]
Not an issue with the bot. You haven't defined `experienceLevel` which is an expected input from you. Closing.

**Comment by voidbydefault** [comment]
PS: Just to help you out, copy and paste this (change True/False as suitable to you):

```
experienceLevel:
 internship: False
 entry: False
 associate: False
 mid-senior level: True
 director: True
 executive: True
```

**Comment by syosry** [comment]
Good morning!

Thank you for your response. I am still having the same issue. I have
filled out experience level how you have done it and it does the same error
with job types as well. I have attached a screenshot of that part of my
code.

Thanks, Salma

**Comment by voidbydefault** [comment]
Good day @syosry ,

There is no screenshot, it's not bot related issue. It seems you have caused unnoticed changes in `config.yaml`, hence it's better take a fresh `config.yaml` and add configs again.
