### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by lakshnocode** [voidbydefault/EasyApplyBot#67]
Tried everything mentioned for the solution
updating chrome to latest version, update pycharm packages... restarting pc. 
deleting chromedriver folder but the issue still remain. please help
![Screenshot 2024-09-26 165424](https://github.com/user-attachments/assets/5ef17c59-975c-490d-bcd9-bad1c1a6ed7a)

**Comment by voidbydefault** [comment]
It's a `chromedriver` issue, not with bot. Did you try deleting this directory? 

> C or D:\Users<user-name>.wdm\drivers\chromedriver

**Comment by lakshnocode** [comment]
Hey thanks for replying yes i did. deleted the directory issue is still there .i think there's issue with newer chrome version. i cant downgrade the version as i have so much data in the chrome browser that i don't want to lose.

**Comment by lakshnocode** [comment]
* Update: Got the perfect solution for running EasyApplyBot!
 
 * You can select the ChromeDriver version that matches your installed Chrome version, even with the latest releases.
 * Here’s how to do it:
 
 * 1. **Download the Compatible ChromeDriver**: Use the version that corresponds to your Chrome installation.
   You can find compatible versions here: https://chromedriver.chromium.org/downloads
 
 * 2. **Modify main.py**: Add the path to your manually downloaded chromedriver.exe in the init_browser function.
 
 * Here’s how your code should look:
 
 from selenium.webdriver.chrome.service import Service
 
 def init_browser():
      chrome_driver_path = "C:\Users\laksh\.wdm\drivers\chromedriver\chromedriver.exe"
     service = Service(chrome_driver_path)
     driver = webdriver.Chrome(service=service)    
      return driver


  This ensures that the bot runs smoothly without compatibility issues!

**Comment by voidbydefault** [comment]
> chrome_driver_path = "C:\Users\laksh.wdm\drivers\chromedriver\chromedriver.exe"
> service = Service(chrome_driver_path)
> driver = webdriver.Chrome(service=service)

Not feasible. You have no idea what kind of queries I get -- people can't do `config.yaml` right which is usually True/False with detailed instructions in comments. Expecting them to manually change path is quite optimistic. Currently it's auto managed. Thanks for suggestion though.
