### ISSUE TITLE
Facing issue while applying

### ISSUE THREAD

**Issue by Omkar1435** [voidbydefault/EasyApplyBot#68]
I am in Germany and when applying to job, code is not able to recognise German terms in Email as E-Mail-Adresse , country as landesvorwahl and randomly picking up country code as well as mobile number as Handynummer

![Capture_LI](https://github.com/user-attachments/assets/ceb88cff-878f-4134-9cf7-47e928828ea3)

**Comment by voidbydefault** [comment]
Bot can only handle English job posts.

**Comment by voidbydefault** [comment]
Tip: Try changing your profile language to English. It should help.
