### ISSUE TITLE
hey bro ! can we collaborate

### ISSUE THREAD

**Issue by rushi1222** [voidbydefault/EasyApplyBot#72]
You're doing great work for job seekers like me! I’ve created an Amazon auto-apply bot and previously used your LinkedIn auto-apply. I know LinkedIn uses dynamic classes to block bots, and I’ve tried a few fixes myself. You seem ahead in this! Would you be open to collaborating via Zoom or Google Meet? I’d love to help!

my email id - k.eswar15108@gmail.com

**Comment by rushi1222** [comment]
i know the core idea is they can change a few dynamic classes but they dont change ui ! so structure is same ! as long as we find the static parts of it and reply element structure we can work this around ! i would love to hear your thoughts

**Comment by rushi1222** [comment]
i know there is an issue with additonal questions ! maybe we can solve it together

**Comment by voidbydefault** [comment]
Hi @rushi1222 

I will drop you an email in a day or so. 

I am not a full time Python programmer, it's just my hobby and finance is my day job (basically a CMA/CA finalist).

> Finding static parts:
You can review my latest code pushed 2 or 3 days ago. I am using xpath to extract dynamic value to feed to bot. 

> Additional questions:
I have fixed almost all of the issues, only need to figure out the section for additional questions. Tried a few things already, none worked. Bot is able to complete job application as long as there are no additional questions. 

This is not an issue so I will be closing this thread. See you in email.
