### ISSUE TITLE
Issue with new code

### ISSUE THREAD

**Issue by ausnaround** [voidbydefault/EasyApplyBot#9]
After following the steps carefully. get this error when running in oycharm. 
C:\Users\user\AppData\Local\Programs\Python\Python311\python.exe C:\Users\user\Desktop\EasyApplyBot-master\EasyApplyBot-master\main.py 
Traceback (most recent call last):
  File "C:\Users\user\Desktop\EasyApplyBot-master\EasyApplyBot-master\main.py", line 113, in <module>
    parameters = validate_yaml()
                 ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\EasyApplyBot-master\EasyApplyBot-master\main.py", line 86, in validate_yaml
    assert isinstance(checkboxes['securityClearance'], bool)
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'securityClearance'

**Comment by ausnaround** [comment]
Hi I solved this by adding this securityClearance: True to checkbox in cofig.yaml

**Comment by voidbydefault** [comment]
Glad you solved it. There is no issues as I have been repeatedly telling users. Closing this thread. Thanks for using my bot.
